# Site settings
title: Informatikunterricht mit Python
locale: de_DE
email: f/xgebkgvl
url: https://tna76874.github.io/notebooks-school
description: "moderner Unterricht mit Python-Notebooks"
keywords: "Informatikunterricht, Python, Schule, Jupyter, Notebook"
skills: "moderner Unterricht mit Python-Notebooks"
meta_author: LMH

binder_commit: 61147dc15394dab240c603760a786aa817aca8ca

blockly_url: 

urlcollection:
  blockly:
    title: Blockly
    url: https://trinket.io/embed/blocks/600acf523e
  
  webassemblypython: 
    title: Python Lite
    url: https://tna76874.github.io/pythonlite/lab/index.html

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 000000 #80B3FF
  primary-rgb: "178, 178, 178" #"128,179,255"
  secondary: b2b2b2 #FD6E8A
  secondary-dark: b2b2b2 #A2122F

# Footer settings
footer:
  copyright: tna76874
  location: ''
  social: ''
  credits: ''

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/tna76874/notebooks-school

githubrepo_python: https://github.com/tna76874/notebooks-school
githubrepo_pythonlite: https://github.com/tna76874/pythonlite
githubrepo_info: https://github.com/tna76874/notebooks-school-info

# Postal address (add as many lines as necessary)
address:

# Credits content
credits: 'Freelancer theme by <a href="https://jekyllthemes.io/theme/freelancer-theme">jekyllthemes.io</a>'

# Build settings
markdown: kramdown
permalink: pretty

collections:
  content:
    people: true

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

exclude:
  - docker-compose.yml

plugins:
  - jekyll-seo-tag